/* eslint-disable import/prefer-default-export */
// https://vuex.vuejs.org/guide/mutations.html#using-constants-for-mutation-types
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUPS = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUPS';
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUP_LIST_ITEMS = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUP_LIST_ITEMS';
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUP_SEARCH_KEYWORD = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUP_SEARCH_KEYWORD';
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUP_FOCUS = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUP_FOCUS';
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUP_BLUR = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUP_BLUR';
export const PHYSICAL_GROUP__SET_PHYSICAL_GROUP_CLICK = 'PHYSICAL_GROUP__SET_PHYSICAL_GROUP_CLICK';
export const PHYSICAL_GROUP__SET_SELECTABLE_H3_LIST = 'PHYSICAL_GROUP__SET_SELECTABLE_H3_LIST';

export const DIRECTOR_APPROVE_LIST__SET_LIST = 'DIRECTOR_APPROVE_LIST__SET_LIST';
export const DIRECTOR_APPROVE_LIST__SET_TOTAL_CNT = 'DIRECTOR_APPROVE_LIST__SET_TOTAL_CNT';
export const DIRECTOR_APPROVE_LIST__SET_QUERY = 'DIRECTOR_APPROVE_LIST__SET_QUERY';
export const DIRECTOR_APPROVE_LIST__SET_PAGINATION = 'DIRECTOR_APPROVE_LIST__SET_PAGINATION';
export const DIRECTOR_APPROVE_LIST__APPROVE_DIRECTOR = 'DIRECTOR_APPROVE_LIST__APPROVE_DIRECTOR';
export const DIRECTOR_APPROVE_LIST__REJECT_DIRECTOR = 'DIRECTOR_APPROVE_LIST__REJECT_DIRECTOR';

export const DIRECTOR_LIST__SET_LIST = 'DIRECTOR_LIST__SET_LIST';
export const DIRECTOR_LIST__SET_TOTAL_CNT = 'DIRECTOR_LIST__SET_TOTAL_CNT';
export const DIRECTOR_LIST__SET_QUERY = 'DIRECTOR_LIST__SET_QUERY';
export const DIRECTOR_LIST__SET_PAGINATION = 'DIRECTOR_LIST__SET_PAGINATION';

export const DIRECTOR_GROUP_LIST__SET_LIST = 'DIRECTOR_GROUP_LIST__SET_LIST';
export const DIRECTOR_GROUP_LIST__SET_TOTAL_CNT = 'DIRECTOR_GROUP_LIST__SET_TOTAL_CNT';
export const DIRECTOR_GROUP_LIST__SET_QUERY = 'DIRECTOR_GROUP_LIST__SET_QUERY';
export const DIRECTOR_GROUP_LIST__SET_PAGINATION = 'DIRECTOR_GROUP_LIST__SET_PAGINATION';
export const DIRECTOR_GROUP_LIST__SET_DIRECTOR_GROUP = 'DIRECTOR_GROUP_LIST__SET_DIRECTOR_GROUP';
export const DIRECTOR_GROUP_LIST__SET_DIRECTOR_GROUP_SEARCH_KEYWORD = 'DIRECTOR_GROUP_LIST__SET_DIRECTOR_GROUP_SEARCH_KEYWORD';
export const DIRECTOR_GROUP_LIST__SET_PHYSICAL_GROUP_LIST = 'DIRECTOR_GROUP_LIST__SET_PHYSICAL_GROUP_LIST';
export const DIRECTOR_GROUP_LIST__SET_PHYSICAL_GROUP_LIST_SEARCH_KEYWORD = 'DIRECTOR_GROUP_LIST__SET_PHYSICAL_GROUP_LIST_SEARCH_KEYWORD';
export const DIRECTOR_GROUP_LIST__SET_PAGE_MODE = 'DIRECTOR_GROUP_LIST__SET_PAGE_MODE';
export const DIRECTOR_GROUP_LIST__SET_DIRECTOR_LIST = 'DIRECTOR_GROUP_LIST__SET_DIRECTOR_LIST';
export const DIRECTOR_GROUP_LIST__CLEAR_DIRECTOR_GROUP = 'DIRECTOR_GROUP_LIST__CLEAR_DIRECTOR_GROUP';

export const DRIVER_APPROVE_LIST__SET_LIST = 'DRIVER_APPROVE_LIST__SET_LIST';
export const DRIVER_APPROVE_LIST__SET_TOTAL_CNT = 'DRIVER_APPROVE_LIST__SET_TOTAL_CNT';
export const DRIVER_APPROVE_LIST__SET_QUERY = 'DRIVER_APPROVE_LIST__SET_QUERY';
export const DRIVER_APPROVE_LIST__SET_PAGINATION = 'DRIVER_APPROVE_LIST__SET_PAGINATION';
export const DRIVER_APPROVE_LIST__APPROVE_DRIVER = 'DRIVER_APPROVE_LIST__APPROVE_DRIVER';
export const DRIVER_APPROVE_LIST__REJECT_DRIVER = 'DRIVER_APPROVE_LIST__REJECT_DRIVER';

export const AUTH__SET_USER_DATA = 'AUTH__SET_USER_DATA';
export const AUTH__CLEAR_USER_DATA = 'AUTH__CLEAR_USER_DATA';

export const ALERT__ADD_ALERT = 'ALERT__ADD_ALERT';
export const ALERT__REMOVE_ALERT = 'ALERT__REMOVE_ALERT';

export const ERROR__ADD_ERROR = 'ERROR__ADD_ERROR';
export const ERROR__CLEAR_ERRORS = 'ERROR__CLEAR_ERRORS';
