export default {
  PHONE_NUMBER: 'PHONE_NUMBER',
  PERSON_NAME: 'PERSON_NAME',
  PASSWORD_WEAK: 'PASSWORD_WEAK',
  PASSWORD_STRONG: 'PASSWORD_STRONG',
  EMAIL: 'EMAIL',
  DIRECTOR_GROUP_NAME: 'DIRECTOR_GROUP_NAME',
};
