export default {
  EVENT: {
    CLIENT: {
      DISPATCH: 'dispatch',
      REDISPATCH: 'reDispatch',
      GROUP_CHANGE: 'groupChange',
      SUB_DELIVERY_GRAB: 'subDeliveryGrab',
      SUB_DELIVERY_GRAB_CANCEL_SUCCESS: 'subDeliveryGrabCancelSuccess',
      PICKUPWISHAT_CHANGE: 'pickupWishAtChange',
      DROP_POINT_CHANGE: 'dropPointChange',
      MEMO_CHANGE: 'memoChange',
      PAYMENT_CHANGE: 'paymentChange',
      PHONE_CHANGE: 'phoneChange',
      DELAY_ACCEPT: 'delayAccept',
      DELAY_REJECT: 'delayReject',
      DELIVERY_CANCEL: 'deliveryCancel',
      DELAY_ASK_MANUAL: 'delayAskManual',
      OPTION_FEE_DRIVER_CREATE: 'optionFeeDriverCreate',
    },
    ROOM: { // 이 이벤트는 Delivery 채널 관련 이벤트임. 비지니스 로직 기반으로 작성됨.
      ROOM_DISPATCH: 'roomDispatch',
      ROOM_REDISPATCH: 'roomReDispatch',
      ROOM_GROUP_CHANGE: 'roomGroupChange',
      ROOM_SUB_DELIVERY_GRAB: 'roomSubDeliveryGrab',
      ROOM_SUB_DELIVERY_GRAB_CANCEL_SUCCESS: 'roomSubDeliveryGrabCancelSuccess',
      ROOM_SUB_DELIVERY_GRAB_CANCEL_FAIL: 'roomSubDeliveryGrabCancelFail',
      ROOM_SUB_DELIVERY_STATUS_CHANGE: 'roomSubDeliveryStatusChange',
      ROOM_PICKUPWISHAT_CHANGE: 'roomPickupWishAtChange',
      ROOM_DROP_POINT_CHANGE: 'roomDropPointChange',
      ROOM_MEMO_CHANGE: 'roomMemoChange',
      ROOM_PAYMENT_CHANGE: 'roomPaymentChange',
      ROOM_PHONE_CHANGE: 'roomPhoneChange',
      ROOM_DELAY_ACCEPT: 'roomDelayAccept',
      ROOM_DELAY_REJECT: 'roomDelayReject',
      ROOM_DELIVERY_CANCEL: 'roomDeliveryCancel',
      ROOM_OPTION_FEE_DRIVER_CREATE: 'roomOptionFeeDriverCreate',
      ROOM_OPTION_FEE_REQUESTER_CREATE: 'roomOptionFeeRequesterCreate',
    },
  },
  CHANNEL: 'delivery',
};
